# Generated by Django 5.0.4 on 2024-07-25 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
